version: "3"

services:

  integration_tests:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - docker-compose.env

  microservices:
    image: "eth-optimism/rollup-microservices:${MICROSERVICES_TAG}"
    volumes:
      - l1-node-data:/mnt/l1-node:rw
      - l2-node-data:/mnt/l2-node:rw
    env_file:
      - docker-compose.env

  l1_chain:
    image: trufflesuite/ganache-cli:latest
    entrypoint: node /app/ganache-core.docker.cli.js -p 9545 --gasPrice="0x0" --callGasLimit="0x1fffffffffffff" --gasLimit="0x1fffffffffffff" --account="0xdf8b81d840b9cafc8cd68cf94f093726b174b5f109eba11a3f2a559e5f9e8bce,1000000000000000000000" --account="0x06caa6f48604a58872e27db8c2980584e20faab37613f51383bb5be62db80c50,100000000000000000000"
    ports:
      - 9545:9545

  postgres:
    image: "eth-optimism/postgres:${POSTGRES_TAG}"
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - docker-compose.env
    ports:
      - 5432:5432

  geth_l2:
    image: "eth-optimism/geth:${GETH_L2_TAG}"
    volumes:
      - l2-node-data:/mnt/l2-node/l2:rw
    env_file:
      - docker-compose.env
    ports:
      - 8545:8545

volumes:
  l1-node-data:
  l2-node-data:
  postgres:
