FROM node:11

# Used to mount the code so image isn't re-built every time code changes
WORKDIR /mnt/integration-tests

# This is required for the wait_for_postgres script
RUN apt-get update
RUN apt-get install -y postgresql-client
# TODO(mark): remove `--ignore-engines` after upgrading node version
RUN yarn global add --ignore-engines wsrun rimraf typescript mocha

ENTRYPOINT [ "bash", "./exec/build_and_run.sh", "yarn", "run", "ci" ]
